---
# Blue Deployment for Django Messaging App (current/stable version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
        - name: messaging-app
          image: messaging_app-web:2.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DB
              value: "messaging_db"
            - name: MYSQL_USER
              value: "messaging_user"
            - name: MYSQL_PASSWORD
              value: "messaging_password"
            - name: MYSQL_HOST
              value: "db"
            - name: MYSQL_PORT
              value: "3306"
          command:
            - sh
            - -c
            - |
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
